import { ClientProfilePictureLarge } from "@/assets";

import { Client } from "./types";

const clients: Client[] = [
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "a",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ahujk",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ahjk",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ctya",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "olua",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ayvu",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ikigvba",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aikugb",
  },
  {
    name: "Andreia do Carmo Nogueira",
    username: "andreia-do-carnmo-nogueira",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "iku",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aikgbik",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "guigigva",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aiuuiygv",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "auivvy789",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "98tg9ia",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "a897tg",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "0gf8ua",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "a87ttggv",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "at675",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "a56dut5",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "7r7fua",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "7fujkla",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "8t7dyta",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "at8795d6",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "6yjrs54a",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "atgyr6yd7",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "artxdtr",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "atdxrtr",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ttyia",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "7dyyya",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "65dydytya",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ad567d6y75",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "sertja",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "atyetse",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aaer5rtr",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "iuiluila",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aawef",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "anmgjyi",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ayfgxdz",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "jlyjyua",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "azfwq",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "agjnhuiyfszdf",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "artuyj",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "ajykfxg",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "xtrugja",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "azeser",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "agjkl",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aetsqw",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "agjxrhktsr",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "hettikya",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "tjgnjxxa",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aykyolyoydxck",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "aserha",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "zehhkta",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "tyustjsiya",
  },
  {
    name: "Jose Carlos Alberto do Carmo",
    username: "jose-carlos-alberto-do-carmo",
    numberOfEvents: 4,
    profilePicture: ClientProfilePictureLarge,
    id: "atssdrvhjf",
  },
];

export default clients;
